version: '3'

networks:
  test-network:
    driver: bridge

services:
  tests:
    build:
      context: .
      dockerfile: ./test.Dockerfile
    depends_on:
      - db
      - keydb
    networks:
      - test-network
    volumes:
      - ./reports:/go/src/app/reports
  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    volumes:
      - ./sql/migrations/:/docker-entrypoint-initdb.d/
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=ledger_auth"
    restart: on-failure
    networks:
      - test-network
  keydb:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - test-network
