replicaCount: 1

image:
  repository: ghcr.io/bradenrayhorn/ledger-auth
  tag: ${{ github.sha }}
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: "ledger-auth"

container:
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "ledger-auth"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/agent-inject-token: "true"
    vault.hashicorp.com/agent-inject-secret-ca: "rootca/cert/ca"
    vault.hashicorp.com/agent-inject-template-ca: |
      {{ with secret "rootca/cert/ca" -}}
        {{- .Data.certificate }}
      {{- end }}
    vault.hashicorp.com/agent-inject-file-ca: "ca.pem"
    vault.hashicorp.com/agent-inject-secret-env: "kv/ledger/ledger-auth"
    vault.hashicorp.com/agent-inject-template-env: |
      {{ with secret "kv/ledger/ledger-auth" -}}
        {{- range $k, $v := .Data.data }}
          {{- $k }}: "{{ $v }}"{{ "\n" }}
        {{- end }}
      {{- end }}
    vault.hashicorp.com/agent-inject-file-env: "config.yml"
  ports:
  - 8080
  - 9000
  livenessProbe:
    httpGet:
      path: /health-check
      port: 8080
  readinessProbe:
    httpGet:
      path: /health-check
      port: 8080

serviceAccount:
  create: true
  name: "ledger-auth"

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http
  - port: 9000
    targetPort: 9000
    name: grpc

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    ingress.kubernetes.io/custom-request-headers: 'X-Forwarded-For:||X-Real-IP:'
  hosts:
  - host: ${{ secrets.HOST }}
    paths:
    - path: /
      port: 80
  tls:
  - hosts:
    - ${{ secrets.HOST }}
    secretName: ledger-auth-cert

jobs:
  - name: migrate
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/role: "ledger-auth"
      vault.hashicorp.com/agent-pre-populate-only: "true"
      vault.hashicorp.com/agent-inject-secret-env: "kv/ledger/ledger-auth"
      vault.hashicorp.com/agent-inject-template-env: |
        {{ with secret "kv/ledger/ledger-auth" -}}
          {{- range $k, $v := .Data.data }}
            {{- $k | toUpper }}="{{ $v }}"{{ "\n" }}
          {{- end }}
        {{- end }}
      vault.hashicorp.com/agent-inject-file-env: ".env"
    containers:
    - name: migrate
      image: "migrate/migrate:4"
      command: ["/bin/sh"]
      args:
        - -c
        - >-
            set -o allexport &&
            source /vault/secrets/.env &&
            /migrate -source github://bradenrayhorn/ledger-auth/sql/migrations#${{ github.sha }} -database postgres://${PG_USERNAME}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DATABASE} up

resources: {}

nodeSelector: {}

tolerations: []

affinity: {} 
