// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ActiveSession struct {
	SessionID string
	UserID    uuid.UUID
	CreatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Username  string
	Password  string
	Email     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
