// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type ActiveSession struct {
	SessionID string
	UserID    string
	CreatedAt time.Time
}

type User struct {
	ID        string
	Username  string
	Password  string
	Email     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
