name: Build and Push Image

on:
  repository_dispatch:
    types: [build-image]

jobs:

  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check Sha
        run: echo $VALUE
        env:
          VALUE: ${{ github.sha }}

      - name: Login to GitLab registry
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push to registry
        uses: docker/build-push-action@v2
        with:
          repository: registry.gitlab.com/bradenr/ledger-auth:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
