name: Deploy

on:
  repository_dispatch:
    types: [deploy]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - uses: azure/setup-helm@v1
        with:
          version: '3.5.0'
        id: install

      - name: Add Helm Repository
        run: helm repo add bradenrayhorn https://bradenrayhorn.github.io/helm-charts/ && helm repo update

      - name: Bake Manifest
        run: helm template bradenrayhorn/webapp
